# Generated by Django 5.1.4 on 2025-01-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('foster', 'Foster Home'), ('adopter', 'Adopter'), ('admin', 'Admin')], default='adopter', max_length=20),
        ),
    ]
