# Generated by Django 5.1.4 on 2025-01-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
