# Generated by Django 5.1.4 on 2025-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccine_report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
