# Generated by Django 5.1.4 on 2025-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0002_pet_vaccine_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird')], default='Dog', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
