# Generated by Django 5.1.4 on 2025-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0005_cart_delete_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
