# Generated by Django 5.1.4 on 2025-01-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0006_pet_about_pet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='home_environment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='intent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
