# Generated by Django 5.1.4 on 2025-01-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0011_alter_pet_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccinated',
        ),
    ]
