# Generated by Django 5.1.4 on 2025-01-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielapp', '0012_remove_pet_vaccinated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movielapp.payment'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Approved'])), fields=('user', 'pet'), name='unique_active_request'),
        ),
    ]
